{{- if or .Values.secrets.encryptionKey .Values.secrets.jwtSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kappi1.fullname" . }}-secrets
  labels:
    {{- include "kappi1.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.encryptionKey }}
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtSecretKey }}
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | b64enc }}
  {{- end }}
{{- end }}

